aws.dynamodb.local=false
aws.region=${AWS_REGION:us-east-1}

spring.datasource.url=jdbc:postgresql://${AURORA_ENDPOINT:localhost}:5432/keypocdb
spring.datasource.username=${AURORA_USER:poc}
spring.datasource.password=${AURORA_PASSWORD:poc}
spring.jpa.hibernate.ddl-auto=validate
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=2
