spring.application.name=file-processing-poc
server.port=8081
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB
file.processing.work-dir=/tmp/neo-file-processing
file.processing.archive-dir=/tmp/neo-archive
file.processing.age-off.bb-retention-days=365
file.processing.age-off.is-retention-days=180
